service: ssm-mysql

frameworkVersion: ">=1.5.0 <2.0.0"

plugins:
  - serverless-python-requirements

custom:
  ssm: ${opt:ssm_env, 'dev'}

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  memorySize: 128
  timeout: 60
  stackTags:
    Name: ${self:provider:stage}-${self:service}
  environment:
    SSM_ENV: ${self:custom.ssm}
  iamRoleStatements:
    -
      Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:ssm'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'parameter/env/${self:custom.ssm}/*'
    exclude:
      - .vscode
      - .git/**
      - .gitignore
      - scripts/**
      - node_modules/
      - package.json
      - package-lock.json
    excludeDevDependencies: true

functions:
  ssm_mysql:
    name: ${self:provider:stage}-${self:service}
    handler: handler.handler